# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\".\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x12\n\nseq_number\x18\x02 \x01(\x05\"\x1b\n\x04Like\x12\x13\n\x0bmessage_seq\x18\x01 \x01(\x05\x32G\n\x04\x43hat\x12#\n\x0bSendMessage\x12\x08.Message\x1a\x08.Message\"\x00\x12\x1a\n\x08SendLike\x12\x05.Like\x1a\x05.Like\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=14
  _MESSAGE._serialized_end=60
  _LIKE._serialized_start=62
  _LIKE._serialized_end=89
  _CHAT._serialized_start=91
  _CHAT._serialized_end=162
# @@protoc_insertion_point(module_scope)
